# docker-compose.yml for jeetSocial
# Defines web and db services, healthchecks, and environment setup.
# See README.md for usage and troubleshooting.

services:
  web:
    build: .
<<<<<<< HEAD
    command: ./wait-for-db-healthy.sh
=======
    command: /bin/sh -c "chmod +x wait-for-db-healthy.sh && ./wait-for-db-healthy.sh"
>>>>>>> 9f6ae9a (Fix Docker Compose DB startup race: use pg_isready healthcheck and wait-for-db-healthy.sh; update static homepage banner and .gitignore)
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: jeetsocial
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
volumes:
  pgdata:
